### PR TITLE
Fixes Thrive#4444: skip JetBrains build on Windows

### LINKED ISSUE #4444: Fix jetbrains checks not working on Windows due to needing to compile
On Windows compiling the project while running is not possible. So instead of trying to build the project the jetbrains based checks should just print a warning about the caveat on Windows that it requires a separate manual compile to be accurate.

### PR DESCRIPTION
**Pull request by ChevyLevi**
**Brief Description of What This PR Does**
When using Windows platform, Running JetBrain check will use `--no-build` parameter and print a message to remind user to manually rebuild before next check running; other platform will use the default `build` parameter.
Note that both `dotnet run --project Scripts -- check inspectcode` and `dotnet run --project Scripts -- check cleanupcode` is effected

**Related Issues**

Fixes Revolutionary-Games/Thrive#4444

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

File: ScriptsBase/Checks/CleanupCode.cs [hunk 1]
```diff
@@ -24,6 +24,8 @@ protected override async Task RunJetBrainsTool(CodeCheckRun runData, Cancellatio
         startInfo.ArgumentList.Add($"--profile={CleanUpProfile}");
         startInfo.ArgumentList.Add($"--caches-home={JET_BRAINS_CACHE}");
 
+        AddJetbrainsToolRunBuildMode(runData, startInfo);
```
Comment (hhyyrylainen) [inline ScriptsBase/Checks/CleanupCode.cs]: I tried looking in the CleanupCode tool documentation but it does not seem to have a build flag: https://www.jetbrains.com/help/resharper/CleanupCode.html#parameters-for-resharper-settings

So I think that adding the build setting flags for cleanup code is incorrect.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
The change for inspect code tool seems fine, but I had a few other minor concerns.

File: ScriptsBase/Checks/CleanupCode.cs (hunk 1 above)
Comment (ChevyLevi) [reply ScriptsBase/Checks/CleanupCode.cs]: Agreed. Still, the document(https://www.jetbrains.com/help/resharper/CleanupCode.html#run_the_tool) shows that `cleanup code` also requires build to work properly, so I think print the hint message when running `cleanup code` is still required. 
And there may comes a further question: should the hint message only printed once when `cleanup code` and `inspect code` are running together?

Comment (hhyyrylainen) [reply ScriptsBase/Checks/CleanupCode.cs]: Well the build being required for CleanupCode, would mean that we should actually *always* print a warning no matter the platform if the CleanupCode is being used without another check command that does a build (or such a build is prevented on the current platform).

So the exact same warning should not in my opinion be used for CleanupCode as it would not be fully accurate.

**Comment by ChevyLevi** [comment]
Change pushed.
Edit: I forgot to remove a redundant `using Systems;`, so the lint check failed. Now it should pass:)

File: ScriptsBase/Checks/CleanupCode.cs (hunk 1 above)
Comment (hhyyrylainen) [reply ScriptsBase/Checks/CleanupCode.cs]: I think it is fine to not handle this CleanupCode case. The change for InspectCode here now looks fine.
